# 版本信息
FROM primetoninc/jdk:1.8
MAINTAINER stonesfour "sunshilei@caicloud.io"


# change path to your repo dir
COPY target/caicloud-consumer-0.0.1-SNAPSHOT.jar  /caicloud-consumer.jar

EXPOSE 8081

CMD ["java", "-jar", "/caicloud-consumer.jar"]
